---
- name: Update APT package manager
  apt:
    update_cache: yes

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update APT after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

# - name: Add Jenkins key to apt
#   apt_key:
#     url: https://pkg.jenkins.io/debian/jenkins.io.key
#     state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update APT after adding Jenkins repository
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

# Add Google Cloud SDK (gcloud CLI) and kubectl installation
- name: Install gcloud dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg

# Install kubectl
- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Verify kubectl installation
  command: kubectl version --client

# GCloud
# Cập nhật danh sách gói
- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

# Cài đặt các gói cần thiết
- name: Install required packages
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
  become: yes

# Tải và thêm khóa GPG cho Google Cloud SDK
- name: Download Google Cloud SDK GPG key and save to keyring
  command: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg -o /tmp/apt-key.gpg
  become: yes

- name: Convert the GPG key to apt keyring format
  command: gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg /tmp/apt-key.gpg
  become: yes

# Thêm repository cho Google Cloud SDK
- name: Add Google Cloud SDK apt repository
  shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
  become: yes

# Cập nhật APT cache sau khi thêm repository
- name: Update APT cache after adding Google Cloud SDK repo
  apt:
    update_cache: yes
  become: yes

- name: Check if apt-get is running
  command: ps aux | grep '[a]pt'
  register: apt_process
  ignore_errors: yes

- name: Kill the apt-get process if it is running
  command: kill -9 {{ item.pid }}
  loop: "{{ apt_process.stdout_lines | select('search', 'apt') | map('split', ' ') | map('first') | list }}"
  when: apt_process.stdout | length > 0
  ignore_errors: yes

- name: Remove dpkg lock files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/dpkg/lock-frontend
    - /var/cache/apt/archives/lock
  ignore_errors: yes

- name: Reconfigure dpkg
  command: dpkg --configure -a
  ignore_errors: yes

- name: Update apt-get cache
  apt:
    update_cache: yes

# Cài đặt Google Cloud CLI
- name: Install Google Cloud CLI
  apt:
    name: google-cloud-cli
    state: present
  become: yes

# Cài đặt GKE gcloud auth plugin
- name: Install GKE gcloud auth plugin
  apt:
    name: google-cloud-sdk-gke-gcloud-auth-plugin
    state: present
  become: yes
